### ISSUE TITLE
Ce inseamna EDUCATIE si ABILITATI?

### ISSUE THREAD

**Issue by astudor** [astudor/skills-education-performance#10]
Cuvinatul "educatie" are in DexOnline mai multe definitii cu sinonimie partiala 

Selectand cateva mai cuprinzatoare:
EDUCATIE 
= Ansamblu de metode și de măsuri aplicate sistematic (și în cadru organizat) cu scopul formării și dezvoltării însușirilor intelectuale, morale, fizice
= Cunoaștere și practicare a regulilor de conviețuire socială. 
= transmitere a experienței de viață a generațiilor adulte și a culturii către generațiile de copii și tineri

In cadrul definitiilor, ca subiect al educatiei este mentionat: individ, copii, tineri, grupare, societate

ABILITATE
= (Capacitatea de a acționa cu) agerime, pricepere, dexteritate, iscusință, îndemânare, dibăcie

Pentru proiectul nostru, ce inteles alegem pt EDUCATIE si ABILITATI ?

**Comment by astudor** [comment]
In cadrul acestui proiect vad conceptele de **educatie** si **dezvoltare a abilitatilor** orientate catre individ pe treptele: 
1. Bazele de care are nevoie pentru a supravietui
- capacitate de a gestiona bine propriul corp fizic / mental-emotional / suflet
- cunostinte despre cum functioneaza propriul sistem, pentru a-l alimenta cu ce are nevoie, cand are nevoie
- capacitate de iubire si relationare cu alte fiinte: de la grija pentru plante pana la buna-intelegere cu semenii sai
2. Capacitatea de a analiza un sistem / mediu nou si a se adapta la el
Exemple variate si atotcuprinzatoare, de la:
- sistemul social in care se afla
- supravietuirea in natura
Pana la:
- o colectie de informatie pe care are nevoie sa o retina 
- un program pe calculator

**Concluzie**
Daca individul are antrenate abilitatile mentionate la punctul 1 si 2, ulterior poate supravietui, isi poate gasi fericirea si poate excela in orice domeniu practic de care are nevoie si este atras.

**Comment by ladriana** [comment]
la defintia educatiei din dex. as adauga urmatoarele:
EDUCATIE
= Ansamblu de metode și de măsuri aplicate sistematic (" **la nivel teoretic si practic**" și în cadru organizat) cu scopul formării și dezvoltării însușirilor intelectuale, morale, fizice

referitor la conceptul de dezvoltare a abilitatilor in contextul aplicarii inventicii, consider a fi necesara acordata o atentie sporita (pe langa notiunilor subliniate de Andrei) urmatoarelor indemanari/abilitati: imaginatie, reorientare si temporizare.

**Comment by Vali80** [comment]
Sunt de acord cu voi si analizand definitiile, inseamna sa urmarim, in educatie, adica triunghiul care reprezinta informatia (triunghiul fenomen), o invatare/educatie orientata pe valori, creativitate, capacitati cognitive (QI de inteligenta cognitiva), capacitati determinate de vointa si de actiune (adica dorinta de a face ceva), pe cunostinte de baza, pe dezvoltarea de abilitati si competente de utilitate directa ,si aici, ati descris voi abilitati de baza (Andrei si Adriana).
Mai adaug aici si informatia pe puncte care am gandit-o eu, si v-am expus - o si la intalnire, pentru triunghiul fenomen:
butonul-sura=formare (educarea infrastructurii mentale a societatii), senzor=cerinte (necesitati ce vin din nevoia societatii si din functionarea acesteia in contextul noilor provocari, precum globalizare, etc), decident=resura umana competitiva (adica generare sustenabila a unei resurse umane inalt pregatita)

**Comment by astudor** [comment]
In baza parerilor inregistrate pana acum, trag concluzia ca termenul "educatie si abilitati performante", ne duce pe toti cu gandul la **potentarea la nivel de performanta a abilitatilor necesare individului**.

Ca side effect aceasta rezulta intr-o colaborare buna intre indivizi (datorita logicii antrenate in toti + inteligenta emotionala), rezultand mai departe in capatarea abilitatilor de supravietuire si excelare a unui grup/societati.

Fiind vorba despre un **program de performanta** in potentarea abilitatilor. Vorbim despre **educatie structurata** (intentie si planificare)

Triunghiul **FENOMEN** poate fi explicitat drept: potentarea pana la nivel de performanta a abilitatilor necesare individului folosindu-se un plan structurat.

Invit la pareri contrare sau de completare.
