### ISSUE TITLE
Ce inseamna APLICAREA INVENTICII?

### ISSUE THREAD

**Issue by astudor** [astudor/skills-education-performance#11]
Conform DexOnline 
inventica = disciplină care studiază procesul invenției și condițiile stimulării creativității.

Ce inseamna
conditiile stimularii creativitatii = ?
procesul inventiei = ?

Oferiti exemple cat mai concrete prin care explicati ce inteles aduc pentru voi grupurile astea de cuvinte.

**Comment by astudor** [comment]
**Concluzie**
De la caz la caz, procesul inventiei este o combinatie intre:
- imbinarea metodelor de cercetare & feedback loop 
- metode folosire a creativitatii (aplicate constient si structurat, sau nu)

**Motivare**
Cand ma gandesc la "**conditii de stimulare a creativitatii**" imi vin in minte exemple precum:  
- cadru relaxat, in care poti avea dialog interior orientat spre a gasi solutie la o problema
- cadru tensionat care iti actioneaza toate simturile pentru ca este absolut necesar sa vii cu o solutie
- grup de persoane cu diverse experiente care explica cum este rezolvata o problema similara, in domeniul lui de expertiza
- jocuri in care cauti sa imbini lucruri aparent fara legatura. Exemplu "cum ar arata/functiona un telefon mobil care sa te spele pe dinti?" "Cum ar suna o melodie de rock in suprapusa/mixata cu melodie simfonica?
- practic, necesitatea stapanirii tehnicilor marunte intr-unul sau mai multe domenii si combinarea lor pentru a atinge un rezultat nou
- expunere la experiente si metode de antrenare a emisferei cerebrale drepte; a creierului mamelian, care gandeste in imagini si asocieri
- expunere la meditatie si accesarea inspiratiei divine

**Procesul inventiei**
O imbinare a exemplelor anterioare intr-un cadru structurat (sau alternare intre cadru haotic si cadru structurat) catre o finalitate pre-definita sau gasita intamplator. Element fundamental este observarea cu atentie asupra a ce se intampla. 
Exemplu de alternare cadre haotic vs structurat: 
- perioada de observare intensa a unui grup de elemente (sa spunem oameni care merg cu autobuzul)
- sesiune de Brainstorming (orice idee care iti vine in minte) "ce probleme intampina acesti oameni"
- imbinarea ideilor expuse, intr-o structura logica

**Comment by ladriana** [comment]
> 
> 
> Conform DexOnline
> inventica = disciplină care studiază procesul invenției și condițiile stimulării creativității.
> 
> Ce inseamna
> conditiile stimularii creativitatii = ?
> procesul inventiei = ?
> 
> Oferiti exemple cat mai concrete prin care explicati ce inteles aduc pentru voi grupurile astea de cuvinte.

conditiile stimularii creativitatii = crearea cadrului optim pentru stimularea creativitatii
acest cadru optim este variabil (oamenii raspund la simuli diferiti)
procesul inventiei = Succesiune de operații, de stări sau de fenomene prin care  se produce o transformare- evoluție

**Comment by Vali80** [comment]
Asa cum ati descris voi, aici, inventica vizeaza actul creativ, cu ea reusim sa  rezolvam probleme/obstacole prin aplicatii practice, folosindu/ne de notiuni si tehnici ce vizeaza dinamizarea(intarirea)/antrenarea abilitatilor creative, prin instrumente psihologice, inclusiv din aria  psihanalizei, in doua cuvinte "psiholigie curata". 
Prin aceasta, reusim sa punem in lumina, adica sa descoperim, sa cultivam si sa valorificam capacitati/capabilitati pe care fiecare persoana le are, dar (daca e adult, fie nu le foloseste sau nu a fost invatat sa le foloseasca, daca e copil - scoala ar trebui sa intervina sa i le cultive - asta vom urmari noi in proiect) este necesar insusirea unor elemente si tehnici ale psihologiei, pentru punerea in lucru a capacitatilor/capabilitatilor, care au ca rezultat - inovare.
Adaug aici, punctele pe care le-as vedea eu pe triunghiul aplicativ (de context): sursa =performanta inalta, senzor= relevarea capabilitatilor, decident=inovare

**Comment by Vali80** [comment]
Am gasit, pe net un material pe inventica si creativiate, vi/l trimit tuturor in e-mail, cred ca ne ajuta sa facem primii pasi in intelegerea inventicii si cum ar trebui aplicata

**Comment by astudor** [comment]
Din parerile inregistrate pana acum sumarizez:

Pentru intelesul sintagmei "conditii de stimulare a activitatii":

"Crearea cadrului optim pentru stimularea creativitatii"(@ladriana)  este  sinonimic cu ce am gandit eu sub denumirea "metode de stimulare a creativitatii", exemple practice precum brainstorming si thinkTank reprezentand creare de cadru optim pentru asa ceva.  

Atat @ladriana cat si @Vali80 iau in calcul diferenta de la caz la caz, partea psihologica fiind importanta. 

@Vali80 are in vedere antrenarea individuala a creativitatii luand in calcul psihologia umana.
De acord. O creativitate individuala antrenata, este un factor in crearea cadrului optim obtinerii inovatiei.

Procesul inventiei este succesiunea de metode creative si studiere/observare a unui fenomen/proces.

In urma acestor pareri am formulat
**Triunghiul CONTEXT** = proceduri de antrenare si folosire a creativitatii & proceduri de cercetare (aparute uzual in drumul catre obtinerea inovatiei)

Gasesc aceasta formulare mai pe intelesul tuturor decat emblematicul "aplicarea inventicii"

Invit la alte pareri, daca credeti ca aduc ceva diferit.
