### ISSUE TITLE
Stabilire Sursa Senzor Decident

### ISSUE THREAD

**Issue by astudor** [astudor/skills-education-performance#12]
Avand in vedere raspunsurile date pentru definirea cuvintelor EDUCATIEI si ABILITATI, respectiv INVENTICA, care credeti ca ar fi punctele SURSA - SENZOR - DECIDENT pentru fiecare din cele 2 triunghiuri?

[Triunghiul FENOMEN](https://github.com/astudor/skills-education-performance/issues/10#issuecomment-617649491) = potentarea pana la nivel de performanta a abilitatilor necesare individului folosindu-se un plan structurat

[Ttriunghiul CONTEXT](https://github.com/astudor/skills-education-performance/issues/11#issuecomment-617637279) = proceduri de antrenare si folosire a creativitatii & proceduri de cercetare (aparute uzual in drumul catre obtinerea inovatiei)

**Comment by astudor** [comment]
Valentina, ca sa nu mai scrii si pentru a 3-a oara, copiez eu parerea ta aici. Poti reveni asupra ei, in special in urma definitiilor explicite a triunghiurilor, ce sunt enuntate in enunt.

Triunghi Fenomen:
> sursa = formare (educarea infrastructurii mentale a societatii), 
> senzor = cerinte (necesitati ce vin din nevoia societatii si din functionarea acesteia in contextul noilor provocari, precum globalizare, etc)
> decident = resura umana competitiva (adica generare sustenabila a unei resurse umane inalt pregatita)

> ..triunghiul aplicativ (de context):
>  sursa = performanta inalta, 
> senzor = relevarea capabilitatilor, 
> decident = inovare

**Comment by ladriana** [comment]
Triunghi Fenomen:

    sursa = educatia
    senzor = finantarea 
    decident = resura umana competenta

  Triunghi  context:
    sursa = multidisciplinaritatea
    senzor = inovarea
    decident = reprofesionalizare

**Comment by astudor** [comment]
"Program de excelenta in educatie si dezvoltare a abilitatiilor" 
De ce fac proiectul? Pentru ca ma intereseaza ABILITATI PERFORMANTE. Cercetez fenomenul de antrenare a abilitatilor performante.

**TRIUNGHI FENOMEN**
**sursa = dezvoltarea continua**
- ce alimenteaza abilitatile performante?  
(Cunoastere + Structura + Aplicare + Intensitate) * Repetare. Astea insumate dau Dezvoltare Continua. 
- Dezvoltarea Continua este ceea ce formeaza abilitati performante.


**senzor = aprofundarea**
- ce determina schimbarea gradului de stapanire a unei abilitati? 
- ce afecteaza pozitiv sau negativ performanta unei abilitati? 
- performanta depinde de ce anume? 
- cand are loc Dezvoltarea Continua, unde se vede acest lucru?
Cu cat ai mai multa aprofundare, cu atat esti mai performant intr-o abilitate/intr-un domeniu (masurabila). 

*aprofundare = cresterea cunoasterii cu urmatoarea treapta + invatare prin exersare(aplic,gresesc,invat, repet)

**decident/manifestare = progresul gradual**
- cum se modifica fenomenul de abilitati performante, in functie de cum se manifesta senzorul?
- cand ai mai putina/multa aprofundare ce se schimba in fenomenul de dezvoltarea abilitatilor performante? 
Progresul Gradual: cand se diminueaza aprofundarea gradul de progres e mai mic. Cand se adanceste aprofundarea progresul e mare. 

*progresul gradual cuprinde dezvoltare, structura, confirmare

**Sensul vectorilor**
Scopul: buna antrenare a performantelor <=> **dezvoltarea continua**
Cum o obtin?

Progres Gradual -> Dezvoltare Continua
Progres Gradual -> Aprofundare   (adica D -> & )
Aprofundare -> Dezvoltare Continua

*De ce Progres Gradual -> Aprofundare  (D -> &)  ?*
Dezvoltarea continuata pe termen lung se intampla daca se auto-alimenteaza ciclul repetitiv intre aprofundare si progres gradual.
Care din ele apare prima? Care din ele da avant destul cat sa re-genereze ciclul? 
Ambele intrebari au ca raspuns "Progresul Gradual".
 
Cunoasterea (individul face cunostinta cu niste notiuni - nu se confunda cu aprofundarea) are loc in T0. 
In T1 se observa Progresul Gradual: trecere de la a nu stii nimic, la a cunoaste ceva. 
Progresul gradual genereaza dopamina pentru ca include confirmare. Asta duce la dorinta de a face mai mult, adica aprofundare.
Cand exista aprofundare exista progres (gradual) care regenereaza ciclul.

------------------------
**TRIUNGHI CONTEXT**
CONTEXTUL in raport cu FENOMENUL

- APLICAREA procedurilor de antrenare a creativitatii si procedurilor de cercetare (aparute uzual in drumul catre obtinerea inovatiei)
*in raport cu* 
- antrenarea pana la nivel de performanta a abilitatilor necesare individului (folosindu-se un plan structurat) 
*cercetare = experimentare structurata

**Pe scurt:** APLICAREA antrenamentelor de creativitate si experimentare structurata pt a obtine abilitati performante


**sursa = motivatia de a te autodepasi / inova / sparge bariere**  
- ce anume hraneste/genereaza _aplicarea_ metodelor de obtinere a creativitatii si experimentarii structurate, pentru a obtine antrenarea abilitatilor?
- ce anume iti da impulsul si sustine vie dorinta de a antrena creativitatea si experimentarea pentru a-ti obtine abilitati performante? 

**incompletitudinea nivelului abilitatilor in fata necesitatii de solutii** 
- gradul de aprofundare (inbunatatire liniara, in adancime) nu este destul pentru a gasit solutii
- simti ca performanta nu poate fi atinsa fara acesti pasi intermediari sau mai degraba zis complementari

Mi-am crescut o abilitate, aprofundand, pana am ajuns un prag aparent maxim. 
Ca sa o ridic la alt nivel am nevoie sa inovez / sa gasesc lucruri noi la acest domeniu de studiu. Ca sa fac asta am nevoie de creativitate si experimentare structurata. _Daca nu ma preseaza necesitatea de solutii (aparuta intrinsec, din pasiune nebuna, sau extrinsec, din mediului care ma impinge catre aceasta nisa), nici macar nu ma gandesc ca e nevoie sa sparg limitele nivelului de performanta atins pana acum_.

**senzor = capacitatea multidisciplinaritatii**
- ce efect are _aplicarea_ metodelor de antrenare a creativitatii si a experimentarii structurate?  
(atentie! in alta incercare de a gasi raspunsuri am luat-o pe o cale eronata pt ca am intrebat ce determina "gradul" de aplicare. 
- ne intereseaza _aplicarea_ studiului de metode prin care se obtine inovatia, nu GRADUL de aplicare a metodelor in sine)
 
**decident(manifestare): obtinerea rezultatelor** 
- le obtin sau nu in functie de cat de bine cunosc si aplic metode creative si de cercetare

Sensul Vectorilor
Obtinerea rezultatelor -> Capacitatea Multidisciplinaritatii
Obtinerea rezultatelor -> Necesitatea de solutii
Capacitatea Multidisciplinaritatii -> Necesitatea de solutii
