### ISSUE TITLE
Stabiliti Obiectiv SMART care sa defineasca proiectul

### ISSUE THREAD

**Issue by astudor** [astudor/skills-education-performance#13]
SMART = acronim pentru **S**pecific, **M**asurabil, de **A**tins, **R**elevant, incadrat in **T**imp

Facem abstractie de denumirea proiectului asa cum o stim pana acum, si de cuvintele cheie care ni s-au dat la "orizontal" si "vertical". 

Ele ne-au dat o directie de gandire, dar in functie de ce vrem sa facem - cat mai concret si specific, vine de la sine Titlul Proiectului, Fenomenul si Contextul, fara sa ne mai impiedicam de cuvinte.

Propun sa ne expunem cat mai specific viziunea dorita, astfel incat sa raspundem la intrebarile:
1. Cine sunt - ce fel de persoana/entitate, cu ce resurse/influenta ?
2. Ce vreau sa aflu
3. Ce vreau sa fac
4. Pentru cine 
5. Parametrii masurabili pentru ce vreau sa reiasa din proiect
6. Conditii realiste pentru ca obiectivul sa fie atins 
7. Relevant pentru furnizor, cumparator si beneficiar (in orice relatie exista rolurile astea)
8. Timpul in care sa fie implementat/atins obiectivul

Denumirile pentru: proiect, fenomen, context le vom deduce dupa ce convergem pe aceeasi idee in materie de viziune si specificitate.

**Comment by astudor** [comment]
**1. Cine sunt ?**
Producator de materiale si jocuri educative pentru copii si invatatori/parinti care se ocupa de educatia copiilor de varste 5-10 ani.

**2. Ce vreau sa stiu?**
a) Ce abilitati de baza si necesare viitorului apropiat sa serveasca jocurile si materialele educationale facute de mine

b) Ce functionalitati concrete sa aibe jocurile pt a dezvolta aceste abilitati
*functionalitati = fond, forma, mod de functionare

c) In ce ordine (de luat in calcul inclusiv sincron/paralel) este indicat a se "consuma" aceste materiale pentru un individ care incepe la varsta de 5 ani si termina la 10 ani.

**3. Ce vreau sa fac?** 
**a) Jocuri si materiale pt activitati educative** 
- care sa antreneze cele mai importante max 10 abilitati necesare intr-o societate a viitorului apropiat, in care tiparul de gandire imbina creativitatea cu analiza metodica
- care sunt destinate copiilor sanatosi si stabili emotionali, cognitiv specific de varstei de 5-10 ani 
- care sa necesite pt creare investitie max 2000 euro + munca voluntara a min 1 om.
- care sa necesite minim 2h pe zi timp de 3 luni pt a ajunge la performanta in abilitatea antrenata de joc
- care sa fie adresabil atat persoanelor din Romania cat si din alte tari cu valori si probleme similare

**b) Un traseu pentru aceste jocuri,** o continuitate, care cladeste abilitatile in ordinea specifica nivelului cognitiv/emotional/fizic. Traseul incepe de la nivel 1 (aferent unui copil @ 5 ani) si ajunge la nivel 5 (copil 10 ani)

**4. Pentru cine?**
Copil sanatos afectiv/cognitiv specific varstei de 5 ani, care pentru dezvoltarea lui sa foloseasca urnatorii 5 ani uneltele/programele definite de mine.
* Daca jocurile au o continuitate este relevant pentru un copil de 8 ani sa le foloseasca? Ideal este ca jocurile sa depinda destul de putin unele de altele de la un  nivel la altul, astfel incat se pot lua si din mers.

**5. Parametrii masurabili pentru ce imi doresc sa rezulte din proiect:**
- identificare @ 10 cele mai relevante abilitati & competente dpdv al necesitatii unei societati cum am descris-o
- identificare minim 3 metode de joc / jocuri pentru fiecare din cele 10 abilitati
- identificare minim timp necesar pentru practica cu fiecare joc pentru o eficienta de 70% (de definit criterii pt acest %)
- identificare jocuri si activitati care nu necesita investitie mai mult de 2000 euro si max 2 luni de efort voluntar 3 ore pe zi din partea a max un om

**6. Conditii pentru ca proiectul sa fie atins**
- timp disponibil al adultilor care supravegheaza copiii = max 2h pe zi
-  investitie max 2000 euro si max 2 luni de efort voluntar 3 ore pe zi din partea a max un om
- costuri rezonabile pentru cumparatorii finali sau intermediari in cazul unei francize de jocuri/activitati

**7. Relevant** 
- pentru furnizor - sa poata vinde => produse cu sens pentru cumparatori si beneficiari
- pentru cumparatori => ratiuni calitate/pret
- pentru parinti (poate gasim si alte beneficii, de exemplu activitati prin care totodata isi rezolva problemele cotidiene sau activitati care nu necesita prezenta lor)
- pentru copii => activitatile sa fie captivante

**8. Parametrii de timp**
Timp de dezvoltare a jocurilor: 
- max 6 luni pentru concept, prototip, test, re-iterare, finalizare, pentru jocuri / activitati care sa acopere un nivel in conditiile in care o singura persoana lucreaza 3 ore (concentrate!) pe zi 
*un nivel = 1 an

Timp de folosire pentru a obtine rezultate per abilitate antrenata
- min 1.5h pe zi

**Comment by ladriana** [comment]
Parcurgand scenariul propus de catre tine Andrei precizez ca mi se pare a fi unul foarte interesant, complex si totodata provocator (in sensul in care exista posibilitatea reala de a fi implementat!).
Daca si Valentina adera la acest proiect, recomand sa dezbatem toate punctele mai sus mentionate in cadrul unor intalniri ...mie imi este mai usor sa ma exprim verbal.

**Comment by Vali80** [comment]
Andrei, am urmarit cu interes ideea ta,SMART, da, acum inteleg de ce ai ales tema, acest proiect il aveai de ceva vreme strucurat in gandurile tale. Astfel ca, tinand cont ca am ales sa ne formam ca echipa, mergem mai departe si sustinem ideea ta, astfel incat sa o transformam in program de excelenta, dar va fi necesar sa ne ”impedicam de cuvinte”, pentru a face din ideea ta, forma de educatie aplicabila, ai creionat oarecum o directie, categorisind si grupa de varsta, insa va trebui sa stabilim o intalnire si sa discutam punctual toti 3.

Pana atunci, pun aici explicatia d-lui profesor cu privire la educatia de excelenta prin Gifted education, organizatie ce dezvolta programe de excelenta unde si dumnealui activeaza:
De la Wikipedia, enciclopedia liberă
< Portal:Educație
Jump to navigationJump to search

**Educația de excelență**

Fiecare copil este înzestrat de natură cu har și potențial. Educația de excelență (en. Gifted education) este o educație care urmărește să descopere, să dezvolte și să promoveze potențialul tuturor categoriilor de copii, abilitățile și potețialele lor naturale (conceptul "nature and nurture" și “ hranirea potențialului natural) prin intermediul unei educații individualizate, o curriculă de nivel internațional, accelerare, îndrumare, mentorat, un mediu de formare armonioasă, echilibrată, cu personal talentat, cu vocație.

Educația de excelență este o formă a educației de masă cu programe specifice orientate spre dezvoltarea abilităților tuturor copiilor. Această educație este deschisă atât la intrare cât și la ieșire, nefăcând discriminări pe criterii legate de vârstă, sex, rasă, cultură, origine socială, avere, localizare geografică, sau orice alte criterii. Ținând cont și de nevoile speciale ale copiilor cu abilități deosebite de educație specializată, cadrul legislativ actual permite noi condiții de studiu în școli și grădinițe capabile să răspundă eficient nevoilor acestora.

Gifted education urmărește:

- să creeze un mediu armonios pentru dezvoltarea inteligențelor multiple, a creativității umane și a realizării personale
- să crească și să educe indivizii pentru folosirea potențialului lor creativ în slujba dezvoltării lor interioare și a unui mediu echilibrat de viață
- să susțină continuitatea legăurilor de familie puternice
- să întărească fundamentul unei vieți sociale morale și dezvoltarea unor relații naturale, armonioase între indivizi și grupuri 
-educă copii privind protejarea și restabilirea legăturii intime dintre om și natură

Educația de excelență este un termen generic pentru practicile, procedurile și teoriile utilizate în educația copiilor înzestați și talentați. Tinerii sunt uneori identificați ca fiind înzestrați în urma unor teste standard, cu toate că folosirea numai a acestora este insuficientă.

**Comment by astudor** [comment]
Acest tichet s-a incheiat prin aprobarea [scenariului](https://github.com/astudor/skills-education-performance/issues/13#issuecomment-619579982)

Concluzia:
**fenomen** = *dezvoltarea abilitatilor* pe grupa de varsta 5-10 ani *relevante* pt cresterea armonioasa a inteligentelor multiple in vederea realizarii personale

**context** = *folosirea jocului* sub diversele lui forme ca mijloc educativ 

**Posibil nume proiect**: Jocurile - Materiale Educative pentru dezvoltarea armonioasa

**Mantra**: Ne jucam - Ne educam - Ne dezvoltam
