### ISSUE TITLE
Cum denumim triunghiul CONTEXT folosind o cuvinte care releva explicit ce inseamna "aplicarea inventicii" ?

### ISSUE THREAD

**Issue by astudor** [astudor/skills-education-performance#9]
Titlul este: "Excelenta in Educatie si Dezvoltare a Abilitatilor"
Orizontal: Educatie
Vertical: Aplicarea Inventicii

Parerea unanima: 
Triunghiul FENOMEN = Educatie si Dezvoltare de abilitati

Pareri impartite:
Triunghiul CONTEXT = ?

**Comment by ladriana** [comment]
Titlul este: "Excelenta in Educatie si Dezvoltare a Abilitatilor"
Orizontal: Aplicarea Inventicii
Vertical: Educatie

Parerea unanima:
Triunghiul FENOMEN = Educatie si Dezvoltare de abilitati

Pareri impartite:
Triunghiul CONTEXT =  Aplicarea inventicii

**Comment by astudor** [comment]
Adriana, multumesc pentru primul comment din echipa! :)

:)) Ok.
Imi dau seama ca formularea initiala a intrebarii nu transmitea intentia corect. 
Intentia intrebarii este sa descriem in alte cuvinte ce insemna **aplicarea inventicii**, ca sa fie acelasi inteles pentru toata lumea. 

Am observat multa confuzie intre "inventica" si "inventie". 
Comparativ cu "educatie si abilitati" care sunt termeni uzuali, si mai usor de definit, "aplicarea inventicii" pare mai difuz. Ma gandesc sa il reformulam in alte cuvinte.

Vom gasit raspuns la aceasta intrebare ca urmare a ce raspundem la Definirea Termenilor (celelalte 2 task-uri)

**Comment by astudor** [comment]
Redundanta aceasta intrebare. Concluziile fiind trase direct in [tichetul #11](https://github.com/astudor/skills-education-performance/issues/11#issuecomment-617637279)

Closing issue.
